### ISSUE TITLE
파일 정리한 커밋의 커밋 메시지는 어떤게 좋을까요?

### ISSUE THREAD

**Issue by hsh2001** [stevejkang/github-guideline#1]
파일을 일괄되게 폴더로 정리한 커밋의 메시지는 어떻게 작성하는게 좋을까요?

\+ 좋은 문서 감사합니다 :)

**Comment by stevejkang** [comment]
좀 더 명확하게 해보면 **"파일들을 폴더로 넣어 파일 트리 상 depth를 조정했다"** 와 같은 의미로 이해하고 아래와 같이 message를 작성할 수 있을 것 같습니다.
```
Organize files into folders and change the project structure
```
두 동사[`Organize`, `Change`] 모두 문서에는 없지만 필요성이 있다고 생각되어 이 부분은 반영해두도록 하겠습니다. 🙏

**Comment by hsh2001** [comment]
감사합니다 ㅠㅜ 진짜 도움 많이 되고 있어요. 화이팅!! 😁
